import { OVERRIDES_PATH, type Overrides } from '../../builder/src/files';
import type { Crate, CrateRecord } from '../../shared/crate';
import { ApiError, readJson, type EditorDeps, type GitResult } from './deps';

/** The only paths Publish ever stages or commits. */
export const PUBLISH_PATHS = ['crates', OVERRIDES_PATH, 'library/genres.json'];

/** Generated by `npm run genres:mb`; allowed to be dirty without blocking a publish. */
const ALLOWED_DIRTY = new Set(['library/genres-mb.json']);
const UNAVAILABLE = 'unavailable';
const MAX_LISTED = 5;

export interface Change {
  /** Porcelain status letter(s), e.g. "M", "A", "D", "??". */
  status: string;
  path: string;
}

export interface PublishPreview {
  changes: Change[];
  blockers: string[];
  hasRemote: boolean;
  suggestedMessage: string;
}

export interface PublishResult {
  committed: string;
  pushed: boolean;
  output: string;
}

// ---- git helpers ----

function run(deps: EditorDeps, args: string[]): GitResult {
  const r = deps.git(args);
  if (r.code !== 0) {
    const detail = (r.stderr || r.stdout).trim();
    throw new ApiError(500, `git ${args[0]} failed${detail ? `: ${detail}` : ''}`);
  }
  return r;
}

interface StatusEntry extends Change {
  /** The raw two-letter XY code. */
  xy: string;
}

/** Parses `git status --porcelain -z` (renames/copies are followed by their origin path, which is skipped). */
export function parseStatus(out: string): StatusEntry[] {
  const tokens = out.split('\0');
  const entries: StatusEntry[] = [];
  for (let i = 0; i < tokens.length; i++) {
    const t = tokens[i];
    if (t.length < 4) continue;
    const xy = t.slice(0, 2);
    entries.push({ xy, status: xy === '??' ? '??' : xy.trim(), path: t.slice(3) });
    if (xy[0] === 'R' || xy[0] === 'C') i++;
  }
  return entries;
}

const inPublishPaths = (path: string) => PUBLISH_PATHS.some((p) => path === p || path.startsWith(`${p}/`));

/** `crates/<id>.json` → id, or null for anything else (including index.json). */
function crateIdOf(path: string): string | null {
  const m = /^crates\/([^/]+)\.json$/.exec(path);
  return m && m[1] !== 'index' ? m[1] : null;
}

const isDeleted = (e: StatusEntry) => e.xy.includes('D');
const isNew = (e: StatusEntry) => e.xy === '??' || e.xy[0] === 'A';

/**
 * A record is reviewed when it has a Spotify album and either a high match or an override
 * (in overrides.json or on its match), or when it has no album and is overridden "unavailable".
 */
function needsReview(r: CrateRecord, overrides: Overrides): boolean {
  if (r.spotify === null) return overrides[r.rymId] !== UNAVAILABLE;
  const overridden = r.match?.override === true || Object.hasOwn(overrides, r.rymId);
  return r.match?.confidence !== 'high' && !overridden;
}

const plural = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`;

function listPaths(paths: string[]): string {
  const shown = paths.slice(0, MAX_LISTED).join(', ');
  return paths.length > MAX_LISTED ? `${shown} and ${paths.length - MAX_LISTED} more` : shown;
}

// ---- handlers ----

interface Analysis extends PublishPreview {
  /** PUBLISH_PATHS entries that have changes, i.e. what `git add` gets. */
  pathsToAdd: string[];
}

function analyse(deps: EditorDeps): Analysis {
  const all = parseStatus(run(deps, ['status', '--porcelain', '-z', '--untracked-files=all']).stdout);
  const inside = all.filter((e) => inPublishPaths(e.path));
  const outside = all.filter((e) => !inPublishPaths(e.path) && !ALLOWED_DIRTY.has(e.path));
  const overrides = readJson<Overrides>(deps, OVERRIDES_PATH, {});

  const blockers: string[] = [];
  const crateLabels: string[] = [];
  for (const e of inside) {
    const id = crateIdOf(e.path);
    if (!id) continue;
    if (isDeleted(e)) {
      crateLabels.push(`${id} (deleted)`);
      continue;
    }
    let crate: Crate;
    try {
      crate = readJson<Crate>(deps, e.path);
    } catch (err) {
      blockers.push((err as Error).message);
      continue;
    }
    const name = crate.name || id;
    crateLabels.push(isNew(e) ? `${name} (new)` : name);
    const unreviewed = (crate.records ?? []).filter((r) => needsReview(r, overrides)).length;
    if (unreviewed > 0) {
      blockers.push(`${name}: ${plural(unreviewed, 'record still needs', 'records still need')} review`);
    }
  }
  if (outside.length > 0) {
    blockers.push(`Uncommitted changes outside crates — commit or stash them first: ${listPaths(outside.map((e) => e.path))}`);
  }
  if (inside.length === 0) blockers.push('Nothing to publish');

  return {
    changes: inside.map(({ status, path }) => ({ status, path })),
    blockers,
    hasRemote: run(deps, ['remote']).stdout.trim() !== '',
    suggestedMessage: suggestMessage(crateLabels, inside),
    pathsToAdd: PUBLISH_PATHS.filter((p) => inside.some((e) => e.path === p || e.path.startsWith(`${p}/`))),
  };
}

function suggestMessage(crateLabels: string[], inside: StatusEntry[]): string {
  // New crates first, then changed, then deleted; each group keeps git's (path) order.
  const rank = (l: string) => (l.endsWith(' (new)') ? 0 : l.endsWith(' (deleted)') ? 2 : 1);
  const labels = [...crateLabels].sort((a, b) => rank(a) - rank(b));
  if (labels.length > 0) return `Update crates: ${labels.join(', ')}`;
  const touched = [
    inside.some((e) => e.path === 'library/genres.json') && 'genres',
    inside.some((e) => e.path === OVERRIDES_PATH) && 'overrides',
  ].filter(Boolean);
  if (touched.length > 0) return `Update ${touched.join(' and ')}`;
  return inside.length > 0 ? 'Update crates' : '';
}

/** What Publish would do: changed paths, anything blocking it, and a suggested commit message. */
export function previewPublish(deps: EditorDeps): PublishPreview {
  const { changes, blockers, hasRemote, suggestedMessage } = analyse(deps);
  return { changes, blockers, hasRemote, suggestedMessage };
}

/**
 * Commits the publish paths with `message` (no trailers; these are the user's own commits) and
 * pushes when a remote exists. Throws ApiError 409 (body `{ error, blockers }`) while blocked.
 */
export function publish(deps: EditorDeps, message: string): PublishResult {
  if (typeof message !== 'string' || message.trim() === '') throw new ApiError(400, 'A commit message is required');
  const a = analyse(deps);
  if (a.blockers.length > 0) {
    throw new ApiError(409, 'Publish is blocked', { error: 'Publish is blocked', blockers: a.blockers });
  }

  run(deps, ['add', '-A', '--', ...a.pathsToAdd]);
  // Pathspec on commit, so nothing else that happens to be staged sneaks in.
  const commit = run(deps, ['commit', '-m', message.trim(), '--', ...a.pathsToAdd]);
  const committed = run(deps, ['rev-parse', 'HEAD']).stdout.trim();
  const output = [commit.stdout, commit.stderr].filter(Boolean).join('');

  if (!a.hasRemote) return { committed, pushed: false, output };

  const push = deps.git(['push']);
  const pushOutput = [push.stdout, push.stderr].filter(Boolean).join('');
  if (push.code !== 0) {
    const error = `Committed ${committed}, but git push failed: ${(push.stderr || push.stdout).trim()}`;
    throw new ApiError(500, error, { error, committed, pushed: false, output: output + pushOutput });
  }
  return { committed, pushed: true, output: output + pushOutput };
}
